### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by treesofgroo** [treesofgroo/Ios-Calculator#1]
- [ ] 숫자를 눌렀을 때 해당 숫자 값 정하고 화면에 나타내기
- [ ] AC 누르면 값 초기화하기
- [ ] C 버튼 만들고 적용하기
- [ ] 연산자 클릭할 때 해당 연산자로 계산하기
- [ ] 소숫점 표현하기
- [ ] 퍼센트 표현하기
- [ ] +/- 표현하기
